# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define a global platform for your project
platform :ios, '8.0'

# Define workspace
workspace 'SciChart.iOS.Tutorials'
 
use_frameworks! 
def scichart_pod
    pod 'SciChart', '~> 4'
end
 
# Define project targets
target 'Tutorial 01 - Create a simple 2D Chart' do 
    project 'Tutorial 01 - Create a simple 2D Chart/Tutorial 01 - Create a simple 2D Chart.xcodeproj'
    scichart_pod 
end
target 'Tutorial 02 - Zooming and Panning Behavior' do
    project 'Tutorial 02 - Zooming and Panning Behavior/Tutorial 02 - Zooming and Panning Behavior.xcodeproj'
    scichart_pod
end
target 'Tutorial 03 - Tooltips and Legends' do
    project 'Tutorial 03 - Tooltips and Legends/Tutorial 03 - Tooltips and Legends.xcodeproj'
    scichart_pod
end
target 'Tutorial 04 - Adding Realtime Updates' do
    project 'Tutorial 04 - Adding Realtime Updates/Tutorial 04 - Adding Realtime Updates.xcodeproj'
    scichart_pod
end
target 'Tutorial 05 - Annotations' do
    project 'Tutorial 05 - Annotations/Tutorial 05 - Annotations.xcodeproj'
    scichart_pod
end
target 'Tutorial 06 - Multiple Axis' do
    project 'Tutorial 06 - Multiple Axis/Tutorial 06 - Multiple Axis.xcodeproj'
    scichart_pod
end
target 'Tutorial 07 - Linking Multiple Charts' do
    project 'Tutorial 07 - Linking Multiple Charts/Tutorial 07 - Linking Multiple Charts.xcodeproj'
    scichart_pod
end