platform :ios, '15.0'

source 'https://github.com/ABTSoftware/PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PerformanceComparison' do
  use_frameworks!

  pod 'SciChart'
  pod 'DGCharts', :git => 'https://github.com/danielgindi/Charts.git'
  pod 'ChartsRealm'
  pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
  
end
