uniform highp mat4 matProj;
uniform highp mat4 matWorldView;
uniform highp mat4 TexCoordsPosDeltaMap;
uniform highp vec4 Text2DRotationData;
uniform highp vec4 Text2DDepthData;
attribute highp vec4 vPosition;
attribute highp vec2 vTexCoord0;
attribute highp vec4 vColor;
varying highp vec4 xlv_TEXCOORD0;
varying highp vec4 xlv_COLOR0;
void main ()
{
  highp vec4 tmpvar_1;
  highp vec4 tmpvar_2;
  highp vec4 tmpvar_3;
  highp vec2 resTexCoord_4;
  highp int tmpvar_5;
  tmpvar_5 = int(vTexCoord0.x);
  highp int tmpvar_6;
  tmpvar_6 = int(vTexCoord0.y);
  resTexCoord_4.x = ((float(mod (float(tmpvar_5), 16.0))) / 16.0);
  resTexCoord_4.y = (float((tmpvar_5 / 16)) / 16.0);
  highp vec4 v_7;
  v_7.x = TexCoordsPosDeltaMap[0][tmpvar_6];
  v_7.y = TexCoordsPosDeltaMap[1][tmpvar_6];
  v_7.z = TexCoordsPosDeltaMap[2][tmpvar_6];
  v_7.w = TexCoordsPosDeltaMap[3][tmpvar_6];
  resTexCoord_4 = (resTexCoord_4 + (0.055 * v_7.xy));
  highp vec4 _position_8;
  _position_8.z = vPosition.z;
  highp vec4 v_9;
  v_9.x = TexCoordsPosDeltaMap[0][tmpvar_6];
  v_9.y = TexCoordsPosDeltaMap[1][tmpvar_6];
  v_9.z = TexCoordsPosDeltaMap[2][tmpvar_6];
  v_9.w = TexCoordsPosDeltaMap[3][tmpvar_6];
  _position_8.xy = (vPosition.xy + (vPosition.w * v_9.zw));
  _position_8.w = 1.0;
  highp vec2 p_10;
  highp float tmpvar_11;
  tmpvar_11 = Text2DRotationData.w;
  highp mat2 tmpvar_12;
  tmpvar_12[0].x = tmpvar_11;
  tmpvar_12[0].y = Text2DRotationData.z;
  tmpvar_12[1].x = -(Text2DRotationData.z);
  tmpvar_12[1].y = tmpvar_11;
  p_10 = (_position_8.xy - Text2DRotationData.xy);
  p_10 = (p_10 * tmpvar_12);
  _position_8.xy = (p_10 + Text2DRotationData.xy);
  tmpvar_1.xyz = _position_8.xyz;
  tmpvar_1.w = 1.0;
  tmpvar_2.xyw = (tmpvar_1 * (matWorldView * matProj)).xyw;
  tmpvar_3.zw = vec2(0.0, 0.0);
  tmpvar_3.xy = resTexCoord_4;
  tmpvar_2.z = Text2DDepthData.x;
  gl_Position = tmpvar_2;
  xlv_TEXCOORD0 = tmpvar_3;
  xlv_COLOR0 = vColor;
}

