# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define workspace
workspace 'SciChart.iOS.Showcase'

# Define projects
project 'SciChartShowcase/SciChartShowcaseDemo.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target SciChartShowcase
target 'SciChartShowcaseDemo' do
    use_frameworks!
    pod 'SciChart', '2.0.0.1312'
    project 'SciChartShowcase/SciChartShowcaseDemo.xcodeproj'
end
