# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define projects
project 'ShareChartSwiftExample.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target SciChartDemo
use_frameworks!
pod 'SciChart', '2.1.0.1901'

# Define pods for target SciChartSwiftDemo
target 'ShareChartSwiftExample' do
project 'ShareChartSwiftExample.xcodeproj'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
