# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define workspace
workspace 'SciChart.iOS.Showcase'

# Define projects
project 'SciChartShowcaseDemo.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target SciChartShowcase
target 'SciChartShowcaseDemo' do
    use_frameworks!
    pod 'SciChart'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
