# Define workspace
workspace 'SciChart.iOS.Showcase'

# Define a global platform for your project
platform :ios, '8.0'

use_frameworks!

# Define pods for target SciChartShowcase
target 'SciChartShowcaseDemo' do
    
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
