# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs3.x.git'
# Define the RxSwift cocoapods source
source 'https://cdn.cocoapods.org/'

# Define workspace
workspace 'SciChart.iOS.Examples'

# Define projects
project 'SciChartDemo.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'
use_frameworks!

# Define pods for target SciChartDemo
target 'SciChartDemo' do
    inherit! :search_paths
    pod 'SciChart', '3.1.0-nightly.5238'
    pod 'RxSwift'
end

target 'SciChartDemoUITests' do
    inherit! :search_paths
    pod 'SciChart', '3.1.0-nightly.5238'
end
