# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs3.x.git'

# Define workspace
workspace 'SciChart.iOS.Examples'

# Define projects
project 'SciChartDemo.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target SciChartDemo
use_frameworks!
pod 'SciChart', '3.0.1-nightly.5108'

target 'SciChartDemo' do
    inherit! :search_paths
    pod 'SciChart', '3.0.1-nightly.5108'
end

target 'SciChartDemoUITests' do
    inherit! :search_paths
    pod 'SciChart', '3.0.1-nightly.5108'
end
