# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'
source 'https://github.com/ABTSoftware/PodSpecs-Nightly.git'
# Define the RxSwift cocoapods source
source 'https://cdn.cocoapods.org/'

# Define workspace
workspace 'SciChart.iOS.Examples'
use_frameworks!
def scichart_pod
    pod 'SciChart', '4.0.0-alpha.5320'
end

# Define pods for target SciChartDemo
target 'SciChartDemo' do
    platform :ios, '11.0'
    project 'SciChartDemo/SciChartDemo.xcodeproj' 
    pod 'RxSwift'
    scichart_pod
end
# Define pods for target SciChartDemo.Mac
target 'SciChartDemo.Mac' do
    platform :osx, '10.13'
    project 'SciChartDemo.Mac/SciChartDemo.Mac.xcodeproj' 
    pod 'RxSwift'
    scichart_pod
end

target 'SciChartDemoUITests' do
    inherit! :search_paths
    scichart_pod
end