# Define the SciChart cocoapods source
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define workspace
workspace 'SciChart.iOS.Examples'

# Define projects
project 'SciChartDemo/SciChartDemo.xcodeproj'
project 'SciChartSwiftDemo/SciChartSwiftDemo.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target SciChartDemo
use_frameworks!
pod 'SciChart', '2.2.1.2265'

target 'SciChartDemo' do
    project 'SciChartDemo/SciChartDemo.xcodeproj'
    target 'SciChartDemoTests' do
        inherit! :search_paths
        pod 'SciChart', '2.2.1.2265'
    end
end

# Define pods for target SciChartSwiftDemo
target 'SciChartSwiftDemo' do
    project 'SciChartSwiftDemo/SciChartSwiftDemo.xcodeproj'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
