# Define the SciChart cocoapods source
source 'https://github.com/ABTSoftware/PodSpecs.git'

# Define workspace
workspace 'SciChart.iOS.Tutorials'

# Define projects
project 'Tutorial02_CreatingASciChartSurface/HavingFunWithSciChart.xcodeproj'
project 'Tutorial03_AddingSeries/HavingFunWithSciChart.xcodeproj'
project 'Tutorial04_Adding_Zooming_Panning/HavingFunWithSciChart.xcodeproj'
project 'Tutorial05_AddingToolTipsAndLegends/HavingFunWithSciChart.xcodeproj'
project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries/HavingFunWithSciChart.xcodeproj'
project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries_FIFO/HavingFunWithSciChart.xcodeproj'
project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries_VisibleRange_Manipulations/HavingFunWithSciChart.xcodeproj'
project 'Tutorial06_AddingRealtimeUpdates_UpdatingDataSeries/HavingFunWithSciChart.xcodeproj'
project 'Tutorial07_Annotations/HavingFunWithSciChart.xcodeproj'
project 'Tutorial08_AddingMultipleAxes/HavingFunWithSciChart.xcodeproj'
project 'Tutorial09_AddingMultipleCharts/HavingFunWithSciChart.xcodeproj'

# Define a global platform for your project
platform :ios, '8.0'

# Define pods for target tutorials
use_frameworks!
pod 'SciChart’, '2.0.0.1505'

# Define pods for target tutorials
target 'HavingFunWithSciChart' do
    project 'Tutorial02_CreatingASciChartSurface/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial03_AddingSeries/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial04_Adding_Zooming_Panning/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial05_AddingToolTipsAndLegends/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries_FIFO/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial06_AddingRealtimeUpdates_AppendingDataSeries_VisibleRange_Manipulations/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial06_AddingRealtimeUpdates_UpdatingDataSeries/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial07_Annotations/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial08_AddingMultipleAxes/HavingFunWithSciChart.xcodeproj'
    project 'Tutorial09_AddingMultipleCharts/HavingFunWithSciChart.xcodeproj'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
